const enc=new TextEncoder();
const dec=new TextDecoder();
export const SESSION_COOKIE='trill_admin_session';
export const SESSION_SECONDS=8*60*60;
const toBase64Url=(bytes)=>{let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');};
const fromBase64Url=(value)=>{const normalized=String(value).replaceAll('-','+').replaceAll('_','/');const padded=normalized+'='.repeat((4-normalized.length%4)%4);const binary=atob(padded);return Uint8Array.from(binary,(char)=>char.charCodeAt(0));};
const normalizeUsername=(value)=>String(value||'').trim().toLowerCase();
export const readUsers=(env)=>{let users;try{users=JSON.parse(env.ADMIN_USERS||'{}');}catch{return {};}return users&&typeof users==='object'&&!Array.isArray(users)?users:{};};
const importHmacKey=(secret)=>crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);
const signValue=async(value,secret)=>toBase64Url(new Uint8Array(await crypto.subtle.sign('HMAC',await importHmacKey(secret),enc.encode(value))));
const safeEqual=(left,right)=>{const a=enc.encode(String(left)),b=enc.encode(String(right));if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0;};
export async function verifyPassword(username,password,env){const users=readUsers(env),record=users[normalizeUsername(username)];if(!record||typeof record!=='object')return false;const salt=String(record.salt||''),expected=String(record.hash||''),iterations=Number(record.iterations||100000);if(!salt||!expected||!Number.isInteger(iterations)||iterations<50000||iterations>500000)return false;const material=await crypto.subtle.importKey('raw',enc.encode(String(password||'')),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:fromBase64Url(salt),iterations,hash:'SHA-256'},material,256);return safeEqual(toBase64Url(new Uint8Array(bits)),expected);}
export async function createSession(username,env){if(!env.SESSION_SECRET)throw Error('SESSION_SECRET is not configured');const payload=toBase64Url(enc.encode(JSON.stringify({u:normalizeUsername(username),exp:Math.floor(Date.now()/1000)+SESSION_SECONDS})));return payload+'.'+await signValue(payload,env.SESSION_SECRET);}
export async function verifySession(request,env){if(!env.SESSION_SECRET)return null;const cookies=String(request.headers.get('cookie')||'').split(';');let token='';for(const part of cookies){const index=part.indexOf('=');if(index<0)continue;if(part.slice(0,index).trim()===SESSION_COOKIE){token=part.slice(index+1).trim();break;}}const pieces=token.split('.');if(pieces.length!==2)return null;let valid=false;try{valid=await crypto.subtle.verify('HMAC',await importHmacKey(env.SESSION_SECRET),fromBase64Url(pieces[1]),enc.encode(pieces[0]));}catch{return null;}if(!valid)return null;let payload;try{payload=JSON.parse(dec.decode(fromBase64Url(pieces[0])));}catch{return null;}const username=normalizeUsername(payload&&payload.u),exp=Number(payload&&payload.exp);if(!username||!Number.isFinite(exp)||exp<=Math.floor(Date.now()/1000))return null;if(!readUsers(env)[username])return null;return {username,exp};}
export const sessionCookie=(token)=>SESSION_COOKIE+'='+token+'; Path=/; Max-Age='+SESSION_SECONDS+'; HttpOnly; Secure; SameSite=Strict';
export const clearSessionCookie=()=>SESSION_COOKIE+'=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict';