import { defineCollection, z } from 'astro:content';

const offices = defineCollection({
  type: 'content',
  schema: z.object({
    published: z.boolean().default(true),
    pageSlug: z.string(),
    block: z.string().default('Trilliant'),
    floor: z.string(),
    area: z.number(),
    rentRate: z.number().default(0),
    rentTax: z.enum(["НДС", "НДФЛ"]).default("НДС"),
    workplaces: z.string(),
    workplacesUz: z.string().default(""),
    workplacesEn: z.string().default(""),
    ready: z.string(),
    readyUz: z.string().default(""),
    readyEn: z.string().default(""),
    officeLayout: z.string(),
    officeLayoutUz: z.string().default(""),
    officeLayoutEn: z.string().default(""),
    title: z.string(),
    titleUz: z.string().default(""),
    titleEn: z.string().default(""),
    detailTitle: z.string(),
    detailTitleUz: z.string().default(""),
    detailTitleEn: z.string().default(""),
    seoTitle: z.string(),
    seoTitleUz: z.string().default(""),
    seoTitleEn: z.string().default(""),
    description: z.string(),
    descriptionUz: z.string().default(""),
    descriptionEn: z.string().default(""),
    imageAlt: z.string().default('Офис в бизнес-центре Trilliant, Ташкент'),
    imageAltUz: z.string().default(""),
    imageAltEn: z.string().default(""),
    intro: z.string(),
    introUz: z.string().default(""),
    introEn: z.string().default(""),
    features: z.array(z.string()).default([]),
    featuresUz: z.array(z.string()).default([]),
    featuresEn: z.array(z.string()).default([]),
    detailFeatures: z.array(z.string()).default([]),
    detailFeaturesUz: z.array(z.string()).default([]),
    detailFeaturesEn: z.array(z.string()).default([]),
    planImage: z.string(),
    mainImage: z.string(),
    gallery: z.array(z.string()).default([]),
    presentationFile: z.string().default('/files/placeholder-presentation-1.pdf'),
    translationLocks: z.array(z.string()).default([]),
  }),
});

export const collections = { offices };
