/* TRILL_ADMIN_SAVE_FUNCTION_START */
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const allowed=new Set(["title","detailTitle","area","floor","workplaces","ready","officeLayout","intro","mainImage","planImage","gallery"]);
const decode=(value)=>{const lf=String.fromCharCode(10),cr=String.fromCharCode(13),cleaned=String(value||"").split(lf).join("").split(cr).join("");const binary=atob(cleaned);return new TextDecoder().decode(Uint8Array.from(binary,(char)=>char.charCodeAt(0)));};
const encode=(value)=>{const bytes=new TextEncoder().encode(value);let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
const yaml=(value)=>Array.isArray(value)?JSON.stringify(value.map((item)=>String(item))):typeof value==="number"?String(value):JSON.stringify(String(value));
const update=(source,fields)=>{const lf=String.fromCharCode(10),crlf=String.fromCharCode(13,10),newline=source.includes(crlf)?crlf:lf,lines=source.split(crlf).join(lf).split(lf);if(lines[0]!=="---")throw Error("Frontmatter start not found");let end=lines.indexOf("---",1);if(end<0)throw Error("Frontmatter end not found");for(const [key,value] of Object.entries(fields)){const prefix=key+":",next=prefix+" "+yaml(value);let index=-1;for(let i=1;i<end;i++){if(lines[i]===prefix||lines[i].startsWith(prefix+" ")){index=i;break;}}if(index>=0){let remove=1;while(index+remove<end){const first=lines[index+remove].charAt(0);if(first!==" "&&first!==String.fromCharCode(9)&&!lines[index+remove].startsWith("- "))break;remove++;}lines.splice(index,remove,next);end=end-remove+1;}else{lines.splice(end,0,next);end++;}}return lines.join(newline);};
export async function onRequestPost({request,env}){if(!request.headers.get("CF-Access-Jwt-Assertion"))return json({error:"Cloudflare Access required"},401);if(!env.GITHUB_TOKEN)return json({error:"GITHUB_TOKEN is not configured"},500);let payload;try{payload=await request.json();}catch{return json({error:"Invalid JSON"},400);}const slug=String(payload&&payload.slug||"").trim();if(!/^[a-z0-9-]+$/.test(slug))return json({error:"Invalid slug"},400);const input=payload&&payload.fields&&typeof payload.fields==="object"&&!Array.isArray(payload.fields)?payload.fields:{},fields={};for(const [key,value] of Object.entries(input))if(allowed.has(key)&&value!==undefined)fields[key]=value;if(typeof fields.gallery==="string"){try{const parsed=JSON.parse(fields.gallery);fields.gallery=Array.isArray(parsed)?parsed.map((item)=>String(item)):[];}catch{fields.gallery=[];}}if(!Object.keys(fields).length)return json({error:"No supported fields"},400);const repo=env.GITHUB_REPO||"SF55SF/trill_admin",branch=env.GITHUB_BRANCH||"main",path="src/content/offices/"+slug+".md",headers={Accept:"application/vnd.github+json",Authorization:"Bearer "+env.GITHUB_TOKEN,"User-Agent":"trilliant-admin","X-GitHub-Api-Version":"2022-11-28"},url="https://api.github.com/repos/"+repo+"/contents/"+path+"?ref="+encodeURIComponent(branch),read=await fetch(url,{headers});if(!read.ok)return json({error:"GitHub read failed",status:read.status},read.status);const current=await read.json(),source=decode(current.content);let updated;try{updated=update(source,fields);}catch(error){return json({error:error instanceof Error?error.message:"Frontmatter update failed"},400);}if(updated===source)return json({ok:true,unchanged:true});const save=await fetch("https://api.github.com/repos/"+repo+"/contents/"+path,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify({message:"Update office "+slug+" from admin",content:encode(updated),sha:current.sha,branch})});if(!save.ok)return json({error:"GitHub save failed",status:save.status,details:await save.text()},save.status);const result=await save.json();return json({ok:true,commit:result.commit&&result.commit.sha||null});}
/* TRILL_ADMIN_SAVE_FUNCTION_END */
