/* TRILL_ADMIN_SAVE_FUNCTION_START */
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const allowed=new Set(["published","title","detailTitle","area","floor","rentRate","rentTax","workplaces","ready","officeLayout","intro","mainImage","planImage","gallery"]);
const decode=(value)=>{const lf=String.fromCharCode(10),cr=String.fromCharCode(13),cleaned=String(value||"").split(lf).join("").split(cr).join("");const binary=atob(cleaned);return new TextDecoder().decode(Uint8Array.from(binary,(char)=>char.charCodeAt(0)));};
const encode=(value)=>{const bytes=new TextEncoder().encode(value);let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
/* TRILL_ADMIN_CREATE_FUNCTION_START */
const yaml=(value)=>{if(Array.isArray(value))return JSON.stringify(value.map((item)=>String(item)));if(typeof value==="number"){if(!Number.isFinite(value))throw Error("Invalid number");return String(value);}if(typeof value==="boolean")return value?"true":"false";return JSON.stringify(String(value));};
const createFrontmatter=(slug,fields)=>{const title=String(fields.title||fields.detailTitle||"Новый офис"),detailTitle=String(fields.detailTitle||title),description=String(fields.intro||("Офис "+title+" в бизнес-центре Trilliant")),area=Number(fields.area||0),rentRate=Number(fields.rentRate||0);const values={published:fields.published===true,pageSlug:slug,block:"Trilliant",floor:String(fields.floor||"1"),area:Number.isFinite(area)?area:0,rentRate:Number.isFinite(rentRate)?rentRate:0,rentTax:fields.rentTax==="НДФЛ"?"НДФЛ":"НДС",workplaces:String(fields.workplaces||"по запросу"),ready:String(fields.ready||"Доступен"),officeLayout:String(fields.officeLayout||"Открытая планировка"),title,detailTitle,seoTitle:title,description,imageAlt:title,intro:String(fields.intro||description),features:[],detailFeatures:[],planImage:String(fields.planImage||"/images/office-2-plan.jpg"),mainImage:String(fields.mainImage||"/images/office-2-photo-1.jpg"),gallery:Array.isArray(fields.gallery)?fields.gallery:[],presentationFile:"/files/placeholder-presentation-1.pdf"};const lines=["---"];for(const [key,value] of Object.entries(values))lines.push(key+": "+yaml(value));lines.push("---","");return lines.join(String.fromCharCode(10));};
/* TRILL_ADMIN_CREATE_FUNCTION_END */
const update=(source,fields)=>{const lf=String.fromCharCode(10),crlf=String.fromCharCode(13,10),newline=source.includes(crlf)?crlf:lf,lines=source.split(crlf).join(lf).split(lf);if(lines[0]!=="---")throw Error("Frontmatter start not found");let end=lines.indexOf("---",1);if(end<0)throw Error("Frontmatter end not found");for(const [key,value] of Object.entries(fields)){const prefix=key+":",next=prefix+" "+yaml(value);let index=-1;for(let i=1;i<end;i++){if(lines[i]===prefix||lines[i].startsWith(prefix+" ")){index=i;break;}}if(index>=0){let remove=1;while(index+remove<end){const first=lines[index+remove].charAt(0);if(first!==" "&&first!==String.fromCharCode(9)&&!lines[index+remove].startsWith("- "))break;remove++;}lines.splice(index,remove,next);end=end-remove+1;}else{lines.splice(end,0,next);end++;}}return lines.join(newline);};
export async function onRequestPost({request,env}){if(!env.GITHUB_TOKEN)return json({error:"GITHUB_TOKEN is not configured"},500);let payload;try{payload=await request.json();}catch{return json({error:"Invalid JSON"},400);}const create=payload&&payload.create===true;const slug=String(payload&&payload.slug||"").trim();if(!/^[a-z0-9-]+$/.test(slug))return json({error:"Invalid slug"},400);const input=payload&&payload.fields&&typeof payload.fields==="object"&&!Array.isArray(payload.fields)?payload.fields:{},fields={};for(const [key,value] of Object.entries(input))if(allowed.has(key)&&value!==undefined)fields[key]=value;if(typeof fields.gallery==="string"){try{const parsed=JSON.parse(fields.gallery);fields.gallery=Array.isArray(parsed)?parsed.map((item)=>String(item)):[];}catch{fields.gallery=[];}}if(!Object.keys(fields).length)return json({error:"No supported fields"},400);const repo=env.GITHUB_REPO||"SF55SF/trill_admin",branch=env.GITHUB_BRANCH||"main",path="src/content/offices/"+slug+".md",headers={Accept:"application/vnd.github+json",Authorization:"Bearer "+env.GITHUB_TOKEN,"User-Agent":"trilliant-admin","X-GitHub-Api-Version":"2022-11-28"},url="https://api.github.com/repos/"+repo+"/contents/"+path+"?ref="+encodeURIComponent(branch),read=await fetch(url,{headers});if(create&&read.ok)return json({error:"Офис с таким адресом уже существует"},409);if(!read.ok){if(!(create&&read.status===404))return json({error:"GitHub read failed",status:read.status,details:await read.text()},read.status);const source=createFrontmatter(slug,fields),createdResponse=await fetch("https://api.github.com/repos/"+repo+"/contents/"+path,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify({message:"Create office "+slug+" from admin",content:encode(source),branch})});if(!createdResponse.ok)return json({error:"GitHub create failed",status:createdResponse.status,details:await createdResponse.text()},createdResponse.status);const created=await createdResponse.json();return json({ok:true,created:true,path,commit:created.commit&&created.commit.sha||null});}const current=await read.json(),source=decode(current.content);let updated;try{updated=update(source,fields);}catch(error){return json({error:error instanceof Error?error.message:"Frontmatter update failed"},400);}if(updated===source)return json({ok:true,unchanged:true});const save=await fetch("https://api.github.com/repos/"+repo+"/contents/"+path,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify({message:"Update office "+slug+" from admin",content:encode(updated),sha:current.sha,branch})});if(!save.ok)return json({error:"GitHub save failed",status:save.status,details:await save.text()},save.status);const result=await save.json();return json({ok:true,commit:result.commit&&result.commit.sha||null});}
/* TRILL_ADMIN_SAVE_FUNCTION_END */
